### ISSUE TITLE
Regarding remote key

### ISSUE THREAD

**Issue by developer8972** [OpenCovidTrace/oextrace-ios#1]
Hi we have been struggling to get access to the "remote key" would you be able to point us in the correct direction or help us identify the remote key. We are getting rolling id and daily key but unable to get the remote key that we receive from other device.

**Comment by alexnivanov** [comment]
Hi, can you please elaborate more by what do you mean by **remote key**?
The data which is exchanged via Bluetooth with other devices is the  RPI which contains rolling id and meta information.

**Comment by developer8972** [comment]
yeah I know that the two devices when they are in near proximity they exchanges keys and I am looking for the key that is coming from other device. 
In our use case we have to send the RPI key received from other devices and local Key(Temporary exposure key from my device)  to our server. we are trying to figure out which location/file would be provide us the RPI key received from other device and pass it to our server. 
It will be really helpful if you can point us to the location/file where we can capture/find these keys.

**Comment by alexnivanov** [comment]
Ok, as you can see, the device own daily key (temporary exposure key) is stored and uploaded from `KeysManager`.
The original use case doesn't upload other contact keys (since the contract is not to process any contact matching on the server). However, they are stored in `BtContactsManager` (for local matching), you can upload them similarly if this is the modification you are looking for.

**Comment by developer8972** [comment]
Hey thanks a lot for the response, 
we are looking at this below file location to retrieve the encounter value( assuming thats the RPI key) but not able to print the value from it. Please let us know if we are not looking at the right spot 
https://github.com/OpenCovidTrace/oextrace-ios/blob/master/oextrace/Services/Persistence/BtContactsManager.swift#L87

it will be really helpful if you can tell us how to access that value.

**Comment by alexnivanov** [comment]
Have a look at this class: `BtContact`.
Each contact may have different "encounters" with corresponding `BtEncounter` class.
The actual `rollingId` is stored in `BtContact`. For 10 minutes interval of 1 `rollingId` there may be different encounters with different meta data (rssi, location, etc.).

**Comment by developer8972** [comment]
so is there any variable defined in this class to get the RPI key value (as a single string), or do we have to capture  the rollingid and metadata and say that as RPI key?

**Comment by alexnivanov** [comment]
Well, that depends on your use case. Basically, rollingId is RPI - it identifies the device itself. Metadata is extra data of the contact (location, time, etc.).
